[package]
name = "tls-examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "0.2.0", path = "../../tokio", features = ["full"] }
tokio-util = { version = "0.2.0", path = "../../tokio-util", features = ["full"] }
tokio-tls={version="0.3.0",path="../../tokio-tls"}
native-tls = "0.2"

[[example]]
name = "echo"
path = "echo.rs"

[[example]]
name = "download-rust-lang"
path = "download-rust-lang.rs"

